services:
  wordpress:
    container_name: wordpress
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - wordpress:/var/www/html
      - ./wp-content:/var/www/html/wp-content
    networks:
      - proxy_network
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_TABLE_PREFIX: emb_
      WORDPRESS_AUTH_KEY:         9c7d28d9cb2f840df9cd377c00787403d411aff2
      WORDPRESS_SECURE_AUTH_KEY:  487d70ee5f38ebda26a370f4f3f425b31ee17dfd
      WORDPRESS_LOGGED_IN_KEY:    54dc65e16672b9f4a00734a3f4dcd13dbb9ee573
      WORDPRESS_NONCE_KEY:        e07d7a158be817486c511a9730b92784fb407077
      WORDPRESS_AUTH_SALT:        52c28af7ae2c92f37060becad5da0a0f5ed5916d
      WORDPRESS_SECURE_AUTH_SALT: 114f963d8225dbcea88926f5fec46433a45decee
      WORDPRESS_LOGGED_IN_SALT:   a90a48f3d683fb09c178ea34fc1e498226e4c2b7
      WORDPRESS_NONCE_SALT:       05c3055a9e30ec3a66b73429490fe8c31daaf02d
    depends_on:
      - mysql

  nginx:
    container_name: nginx
    image: nginx:1.27.2
    restart: unless-stopped
    depends_on:
      - wordpress
    ports:
      - 80:80
    volumes:
      - wordpress:/var/www/html
      - ./wp-content:/var/www/html/wp-content
      - ./nginx-prod:/etc/nginx/conf.d
    networks:
      - proxy_network
  
  mysql:
    image: mysql:9.1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - /var/www/mysql:/var/lib/mysql
    networks:
      - proxy_network

volumes:
  mysql:
  wordpress:
  
networks:
  proxy_network:
    driver: bridge