FROM nginx:1.27.1

ARG NGINX_CONF=stg

COPY conf.d /etc/nginx/conf.d

COPY nginx-${NGINX_CONF}.conf /etc/nginx/nginx.conf

RUN usermod -u 1001 www-data && groupmod -g 1001 nginx

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]