name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download SSH key
        shell: bash
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no root@${{ secrets.SERVER_IP }} exit
      
      - name: Replace the SERVER_NAME in the nginx.conf file with secret
        env:
          SERVER_NAME: ${{ secrets.SERVER_NAME }}
        run: |
          sed -i "s|%SERVER_NAME%|${SERVER_NAME}|g" nginx-prod/nginx.conf

      - name: Build the tailwind.css file
        run: |
          cd wp-content/themes/my-custom-theme
          npm install
          npm run build

      - name: Deploy the website
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
        run: |
          ./deploy.sh