name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Get the SSH key from the secrets and save it to the ssh folder
      - name: Download SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      # Use the ssh key to connect to the server and run the deploy script
      - name: Deploy
        run: |
          SERVER_IP=${{ secrets.SSH_HOST }} sh deploy.sh