name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download SSH key
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{secrets.SSH_HOST}} >> ~/.ssh/known_hosts
      # Use the ssh key to connect to the server and run the deploy script
      - name: Deploy
        env:
          SERVER_IP: ${{ secrets.SSH_HOST }}
        run: |
          ./deploy.sh